"""
World model: convert a parsed PCB tree into a flat list of geometric obstacles.

Each obstacle is a single :class:`shapely.geometry.Polygon` plus metadata
(layer, net, kind, ref). This module is the *only* layer that knows about
KiCad S-expression nodes — everything else in the router package deals with
shapely primitives.

Obstacle kinds
--------------

* ``footprint`` — footprint courtyard AABB (always forbidden for tracks).
* ``pad``       — pad rectangle (SMD) or circle (thru-hole), on its layers.
* ``track``     — existing ``segment`` rectangle, on a single layer, on its net.
* ``via``       — circle, on ``F.Cu`` and ``B.Cu``, on its net.
* ``keepout``   — polygon from a ``(zone (keepout ...))`` node.

A regular ``zone`` with a ``net`` (copper pour) is **not** an obstacle — its
fill is regenerated by KiCad and avoids whatever tracks exist at the time.
"""

from __future__ import annotations

from dataclasses import dataclass, field
import math
from typing import Any, Literal

from shapely.geometry import Point, Polygon

from kcaa.utils.pcb_board_utils import get_fp_courtyard_bbox
from kcaa.utils.pcb_sexp_utils import load_pcb

ObstacleKind = Literal["footprint", "pad", "track", "via", "keepout", "board_edge"]


@dataclass(frozen=True)
class Obstacle:
    """A single geometric obstacle in the world model.

    ``shape`` is the polygon **already buffered** by half the trace width
    (so a thin track is just a thick line). Additional clearance is applied
    by the query layer when checking visibility.
    """

    shape: Polygon
    layers: frozenset[str]
    net: str | None
    kind: ObstacleKind
    ref: str | None = None  # footprint reference for diagnostics


@dataclass
class WorldModel:
    """Container for the obstacle list plus helpers."""

    obstacles: list[Obstacle] = field(default_factory=list)
    board_bbox: tuple[float, float, float, float] | None = None  # (minx, miny, maxx, maxy)

    def on_layer(self, layer: str) -> list[Obstacle]:
        """Return obstacles present on ``layer``."""
        return [o for o in self.obstacles if layer in o.layers]

    def nets(self) -> set[str]:
        return {o.net for o in self.obstacles if o.net}


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def build_world_model(
    pcb_path: str,
    net_filter: str | None = None,
    exclude_refs: set[str] | None = None,
) -> WorldModel:
    """Build a world model from a .kicad_pcb file.

    Args:
        pcb_path: Absolute path to the .kicad_pcb file.
        net_filter: If given, existing tracks/vias on this net are *not*
            treated as obstacles (they belong to the route we're building).
        exclude_refs: Footprint references to exclude entirely (e.g. the
            footprint containing the start/end pad — no point routing around
            itself).

    Returns:
        A populated :class:`WorldModel`.
    """
    data = load_pcb(pcb_path)
    model = WorldModel()
    model.board_bbox = _board_bbox(data)
    exclude_refs = exclude_refs or set()

    for item in data:
        if not _is_list(item):
            continue
        tag = _sym(item[0])
        if tag == "footprint":
            obs = _footprint_obstacle(item, exclude_refs)
            if obs is not None:
                model.obstacles.append(obs)
        elif tag == "segment":
            obs = _segment_obstacle(item, net_filter)
            if obs is not None:
                model.obstacles.append(obs)
        elif tag == "via":
            obs = _via_obstacle(item, net_filter)
            if obs is not None:
                model.obstacles.append(obs)
        elif tag == "zone":
            ko = _keepout_obstacle(item)
            if ko is not None:
                model.obstacles.append(ko)
    return model


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _sym(v: Any) -> str:
    return str(v)


def _is_list(v: Any) -> bool:
    return isinstance(v, list) and len(v) > 0


def _get_sub(node: list[Any], tag: str) -> Any | None:
    for sub in node:
        if _is_list(sub) and _sym(sub[0]) == tag:
            return sub
    return None


def _get_layer_str(node: list[Any]) -> str | None:
    """Return the single explicit layer string of a node, or None."""
    for sub in node:
        if _is_list(sub) and _sym(sub[0]) == "layer" and len(sub) >= 2:
            v = sub[1]
            return v if isinstance(v, str) else _sym(v)
    return None


def _get_net(node: list[Any]) -> str | None:
    """Return the net name from a ``(net ...)`` subnode.

    Supports both legacy ``(net "VCC")`` and KiCad 9+ ``(net 1 "VCC")``
    (id + name) formats.
    """
    sub = _get_sub(node, "net")
    if sub is None or len(sub) < 2:
        return None
    # KiCad 9+: (net <id> "<name>") — name is the last string.
    for v in reversed(sub[1:]):
        if isinstance(v, str):
            return v
        s = _sym(v)
        if s and not s.lstrip("-").isdigit():
            return s
    return None


def _node_xy(node: list[Any], tag: str) -> tuple[float, float] | None:
    sub = _get_sub(node, tag)
    if sub is None or len(sub) < 3:
        return None
    try:
        return float(sub[1]), float(sub[2])
    except (TypeError, ValueError):
        return None


def _node_at3(node: list[Any]) -> tuple[float, float, float]:
    """Parse an ``(at x y [rot])`` subnode. Defaults rot=0."""
    sub = _get_sub(node, "at")
    if sub is None or len(sub) < 3:
        return 0.0, 0.0, 0.0
    try:
        x, y = float(sub[1]), float(sub[2])
        rot = float(sub[3]) if len(sub) >= 4 else 0.0
    except (TypeError, ValueError):
        return 0.0, 0.0, 0.0
    return x, y, rot


def _segment_obstacle(seg_node: list[Any], net_filter: str | None) -> Obstacle | None:
    """Build a track obstacle from a ``segment`` node."""
    start = _node_xy(seg_node, "start")
    end = _node_xy(seg_node, "end")
    if start is None or end is None:
        return None
    w_sub = _get_sub(seg_node, "width")
    if w_sub is None or len(w_sub) < 2:
        return None
    try:
        width = float(w_sub[1])
    except (TypeError, ValueError):
        return None
    layer = _get_layer_str(seg_node)
    if layer is None:
        return None
    net = _get_net(seg_node)
    if net_filter is not None and net == net_filter:
        # Same-net tracks don't block — they are part of the routing we're building.
        return None

    x1, y1 = start
    x2, y2 = end
    half = width / 2.0
    if x1 == x2:
        minx, maxx = x1 - half, x1 + half
        miny, maxy = min(y1, y2), max(y1, y2)
    elif y1 == y2:
        minx, maxx = min(x1, x2), max(x1, x2)
        miny, maxy = y1 - half, y1 + half
    else:
        return Obstacle(
            shape=_oriented_rect(x1, y1, x2, y2, width),
            layers=frozenset({layer}),
            net=net,
            kind="track",
        )
    return Obstacle(
        shape=Polygon([(minx, miny), (maxx, miny), (maxx, maxy), (minx, maxy)]),
        layers=frozenset({layer}),
        net=net,
        kind="track",
    )


def _oriented_rect(x1: float, y1: float, x2: float, y2: float, width: float) -> Polygon:
    """Axis-of-line perpendicular rectangle for a diagonal segment."""
    dx, dy = x2 - x1, y2 - y1
    length = math.hypot(dx, dy)
    if length == 0:
        return Polygon([(x1, y1), (x1, y1), (x1, y1), (x1, y1)])
    px, py = -dy / length * (width / 2.0), dx / length * (width / 2.0)
    return Polygon(
        [
            (x1 + px, y1 + py),
            (x2 + px, y2 + py),
            (x2 - px, y2 - py),
            (x1 - px, y1 - py),
        ]
    )


def _via_obstacle(via_node: list[Any], net_filter: str | None) -> Obstacle | None:
    """Build a via obstacle (circle on F.Cu and B.Cu)."""
    x, y, _ = _node_at3(via_node)
    size_sub = _get_sub(via_node, "size")
    if size_sub is None or len(size_sub) < 2:
        return None
    try:
        size = float(size_sub[1])
    except (TypeError, ValueError):
        return None
    net = _get_net(via_node)
    if net_filter is not None and net == net_filter:
        return None
    return Obstacle(
        shape=Point(x, y).buffer(size / 2.0),
        layers=frozenset({"F.Cu", "B.Cu"}),
        net=net,
        kind="via",
    )


def _keepout_obstacle(zone_node: list[Any]) -> Obstacle | None:
    """If this zone is a keepout, build an obstacle from its polygon."""
    if _get_sub(zone_node, "keepout") is None:
        return None
    layer = _get_layer_str(zone_node)
    if layer is None:
        return None
    polygon_sub = _get_sub(zone_node, "polygon")
    if polygon_sub is None:
        return None
    pts_sub = _get_sub(polygon_sub, "pts")
    if pts_sub is None:
        return None
    coords: list[tuple[float, float]] = []
    for p in pts_sub[1:]:
        if _is_list(p) and _sym(p[0]) == "xy" and len(p) >= 3:
            try:
                coords.append((float(p[1]), float(p[2])))
            except (TypeError, ValueError):
                continue
    if len(coords) < 3:
        return None
    poly = Polygon(coords)
    if poly.is_empty or not poly.is_valid:
        return None
    return Obstacle(shape=poly, layers=frozenset({layer}), net=None, kind="keepout")


def _footprint_obstacle(fp_node: list[Any], exclude_refs: set[str]) -> Obstacle | None:
    """Build a footprint obstacle from its courtyard AABB."""
    fp_x, fp_y, fp_rot = _node_at3(fp_node)
    ref = None
    for sub in fp_node:
        if _is_list(sub) and _sym(sub[0]) == "property" and len(sub) >= 2:
            name = sub[1] if isinstance(sub[1], str) else _sym(sub[1])
            if name == "Reference" and len(sub) >= 3:
                ref = sub[2] if isinstance(sub[2], str) else _sym(sub[2])
                break
    if ref in exclude_refs:
        return None

    bbox = get_fp_courtyard_bbox(fp_node, fp_x, fp_y, fp_rot)
    if bbox is None:
        return None
    poly = Polygon(
        [
            (bbox["min_x"], bbox["min_y"]),
            (bbox["max_x"], bbox["min_y"]),
            (bbox["max_x"], bbox["max_y"]),
            (bbox["min_x"], bbox["max_y"]),
        ]
    )
    return Obstacle(
        shape=poly, layers=frozenset({"F.Cu", "B.Cu"}), net=None, kind="footprint", ref=ref
    )


def _board_bbox(data: list[Any]) -> tuple[float, float, float, float] | None:
    """Compute the AABB of all Edge.Cuts items, or None."""
    xs: list[float] = []
    ys: list[float] = []
    for item in data:
        if not _is_list(item):
            continue
        tag = _sym(item[0])
        if tag not in {"gr_line", "gr_rect", "gr_arc", "gr_circle"}:
            continue
        layer = _get_layer_str(item)
        if layer != "Edge.Cuts":
            continue
        for sub in item:
            if not _is_list(sub):
                continue
            k = _sym(sub[0])
            if k in {"start", "end", "mid", "center"} and len(sub) >= 3:
                try:
                    xs.append(float(sub[1]))
                    ys.append(float(sub[2]))
                except (TypeError, ValueError):
                    pass
    if not xs:
        return None
    return min(xs), min(ys), max(xs), max(ys)
